name: Deploy GitHub Pages with private submodule

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Configure Git to use personal access token for private submodules
      - name: Configure Git for private submodules
        run: |
          git config --global url."https://${{ secrets.HORSEL_ACCESS }}:@github.com/".insteadOf "https://github.com/"

      # Checkout the repository and all submodules
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0  # ensures full history if needed

      # Deploy site to main branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./           # folder containing site + submodules
          publish_branch: main      # deploy to main for user page / custom domain
          force_orphan: false       # keeps branch history intact
